wandb_version: 1

DATALOADER:
  desc: null
  value:
    K_TRANSFORMS: 1
    NUM_WORKERS: 8
    RETURN_IMG0: false
    TEST:
      BATCH_SIZE: 100
      SAMPLER: SequentialSampler
    TRAIN_U:
      BATCH_SIZE: 32
      N_DOMAIN: 0
      N_INS: 16
      SAME_AS_X: true
      SAMPLER: RandomSampler
    TRAIN_X:
      BATCH_SIZE: 32
      N_DOMAIN: 0
      N_INS: 16
      SAMPLER: RandomSampler
DATASET:
  desc: null
  value:
    ALL_AS_UNLABELED: false
    CIFAR_C_LEVEL: 1
    CIFAR_C_TYPE: ''
    NAME: imageNetLT
    NUM_LABELED: -1
    NUM_SHOTS: 0
    ROOT: /nfs/users/ext_amaya.dharmasiri/repos/VL-LTR/data
    SOURCE_DOMAINS: []
    STL10_FOLD: -1
    SUBSAMPLE_CLASSES: all
    TARGET_DOMAINS: []
    VAL_PERCENT: 0.1
INPUT:
  desc: null
  value:
    COLORJITTER_B: 0.4
    COLORJITTER_C: 0.4
    COLORJITTER_H: 0.1
    COLORJITTER_S: 0.4
    CROP_PADDING: 4
    CUTOUT_LEN: 16
    CUTOUT_N: 1
    GB_K: 21
    GB_P: 0.5
    GN_MEAN: 0.0
    GN_STD: 0.15
    INTERPOLATION: bicubic
    NO_TRANSFORM: false
    PIXEL_MEAN:
    - 0.48145466
    - 0.4578275
    - 0.40821073
    PIXEL_STD:
    - 0.26862954
    - 0.26130258
    - 0.27577711
    RANDAUGMENT_M: 10
    RANDAUGMENT_N: 2
    RGS_P: 0.2
    RRCROP_SCALE:
    - 0.08
    - 1.0
    SIZE:
    - 224
    - 224
    TRANSFORMS:
    - random_resized_crop
    - random_flip
    - normalize
MODEL:
  desc: null
  value:
    BACKBONE:
      NAME: RN50
      PRETRAINED: true
      PRETRAINED_PATH: /nfs/users/ext_amaya.dharmasiri/repos/VL-LTR/checkpoints/pretrain_r50_original/checkpoint_50.pth
    HEAD:
      ACTIVATION: relu
      BN: true
      DROPOUT: 0.0
      HIDDEN_LAYERS: []
      NAME: ''
    INIT_WEIGHTS: ''
OPTIM:
  desc: null
  value:
    ADAM_BETA1: 0.9
    ADAM_BETA2: 0.999
    BASE_LR_MULT: 0.1
    GAMMA: 0.1
    LR: 0.002
    LR_SCHEDULER: cosine
    MAX_EPOCH: 20
    MOMENTUM: 0.9
    NAME: sgd
    NEW_LAYERS: []
    RMSPROP_ALPHA: 0.99
    SGD_DAMPNING: 0
    SGD_NESTEROV: false
    STAGED_LR: false
    STEPSIZE:
    - -1
    WARMUP_CONS_LR: 1.0e-05
    WARMUP_EPOCH: 1
    WARMUP_MIN_LR: 1.0e-05
    WARMUP_RECOUNT: true
    WARMUP_TYPE: constant
    WEIGHT_DECAY: 0.0005
OUTPUT_DIR:
  desc: null
  value: output/imagenetLT/CoOp/wikipromptcvlpclip_imagenetLTcomplete/rn50_cvlp/rn50_wikipromptcvlp_0shots/nctx8_cscFalse_ctpend/seed1
RESUME:
  desc: null
  value: output/imagenetLT/CoOp/wikipromptcvlpclip_imagenetLTcomplete/rn50_cvlp/rn50_wikipromptcvlp_0shots/nctx8_cscFalse_ctpend/seed1/prompt_learner
SEED:
  desc: null
  value: 1
TEST:
  desc: null
  value:
    COMPUTE_CMAT: false
    EVALUATOR: Classification
    FINAL_MODEL: last_step
    NO_TEST: false
    PER_CLASS_RESULT: true
    SPLIT: test
TRAIN:
  desc: null
  value:
    CHECKPOINT_FREQ: 1
    COUNT_ITER: train_x
    PRINT_FREQ: 5
TRAINER:
  desc: null
  value:
    CDAC:
      CLASS_LR_MULTI: 10
      P_THRESH: 0.95
      RAMPUP_COEF: 30
      RAMPUP_ITRS: 1000
      STRONG_TRANSFORMS: []
      TOPK_MATCH: 5
    COCOOP:
      CTX_INIT: ''
      N_CTX: 16
      PREC: fp16
    COOP:
      CLASS_TOKEN_POSITION: end
      CSC: false
      CTX_INIT: ''
      N_CTX: 8
      PREC: fp16
    CROSSGRAD:
      ALPHA_D: 0.5
      ALPHA_F: 0.5
      EPS_D: 1.0
      EPS_F: 1.0
    DAEL:
      CONF_THRE: 0.95
      STRONG_TRANSFORMS: []
      WEIGHT_U: 0.5
    DAELDG:
      CONF_THRE: 0.95
      STRONG_TRANSFORMS: []
      WEIGHT_U: 0.5
    DDAIG:
      ALPHA: 0.5
      CLAMP: false
      CLAMP_MAX: 1.0
      CLAMP_MIN: -1.0
      G_ARCH: ''
      LMDA: 0.3
      WARMUP: 0
    DOMAINMIX:
      ALPHA: 1.0
      BETA: 1.0
      TYPE: crossdomain
    ENTMIN:
      LMDA: 0.001
    FIXMATCH:
      CONF_THRE: 0.95
      STRONG_TRANSFORMS: []
      WEIGHT_U: 1.0
    M3SDA:
      LMDA: 0.5
      N_STEP_F: 4
    MCD:
      N_STEP_F: 4
    MEANTEACHER:
      EMA_ALPHA: 0.999
      RAMPUP: 5
      WEIGHT_U: 1.0
    MIXMATCH:
      MIXUP_BETA: 0.75
      RAMPUP: 20000
      TEMP: 2.0
      WEIGHT_U: 100.0
    MME:
      LMDA: 0.1
    NAME: CoOp
    SE:
      CONF_THRE: 0.95
      EMA_ALPHA: 0.999
      RAMPUP: 300
USE_CUDA:
  desc: null
  value: true
VERBOSE:
  desc: null
  value: true
VERSION:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1662381072.896164
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.8.13
      5: 0.13.2
      8:
      - 5
